### ISSUE TITLE
EditText doesn't use style from AppCompat support library

### ISSUE THREAD

**Issue by skatset** [shaubert/masked-input#1]
I found strange things when I use your EditText widget with support library (23.1.1).
The EditText doesn't use style from AppCompat support library (see pictures bellow). I test it for Android 4.0.4 and 2.3.7 versions.

![g2](https://cloud.githubusercontent.com/assets/3938769/12717448/0f1c78e4-c8f9-11e5-84b6-774751ce03ec.png)
![g1](https://cloud.githubusercontent.com/assets/3938769/12717450/10d6caf4-c8f9-11e5-865c-712db9f61d5f.png)

To reproduce this create new application through Android Studio (it should add support library automatically). Then add following line to your application theme in style.xml file:

```
    <item name="colorAccent">#E51937</item>
```

Then insert following code in layout.xml file of a activity:

```
        <android.support.design.widget.TextInputLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
            <EditText
                android:id="@+id/first_name"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/prompt_first_name" />
        </android.support.design.widget.TextInputLayout>


        <android.support.design.widget.TextInputLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
            <com.shaubert.maskedinput.MaskedEditText
                android:id="@+id/phone"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/prompt_phone"
                android:inputType="phone"
                />
        </android.support.design.widget.TextInputLayout>
```

But when I add following properties to your EditText then I have seen almost desired result (but without colored base under the EditText, see picture bellow):

```
                android:background="?attr/editTextBackground"
                android:textColor="?attr/editTextColor"
                android:textAppearance="?android:attr/textAppearanceMediumInverse"
```

![g3](https://cloud.githubusercontent.com/assets/3938769/12717452/122d27c2-c8f9-11e5-8e59-c71da2eb7e23.png)

I use this 3 lines from AppCompat style but when I use this style directly, then I have not seen cursor (test for Android 4.0.4):

```
                style="@style/Widget.AppCompat.EditText"
```

**Comment by shaubert** [comment]
That was because of MaskEditText is direct child of EditText. Changed to AppCompatEditText. Try the latest version `compile 'com.shaubert.maskedinput:library:1.1'`.
