### ISSUE TITLE
It seems that the mi_mask field not used 

### ISSUE THREAD

**Issue by skatset** [shaubert/masked-input#2]
Hello again!

I saw in your documentation that I can use the mi_mask field in a xml file (and it is really good feature!).

But when I specify my mask in the mi_mask field then nothing happens. It seems that the mi_mask field not used.

**Comment by shaubert** [comment]
Hey skatset

Check out [sample](https://github.com/shaubert/masked-input/tree/master/sample). It uses mask from xml attribute on initial launch.

**Comment by skatset** [comment]
I'm sorry. After project cleaning I got correct behavior.
